config/routes.rb
Kosmo::Application.routes.draw do

  get '/promos/58', to: redirect('/services/79-lasernaya-epilyaciya.html')
  get '/promos/top_banner'=>'promos#top_banner'

  resources :faqs

  resources :orders do
      get 'kassa/:id'=>'orders#kassa', on: :collection
      get 'lazer'=>'orders#lazer', on: :collection
      get 'complete'=>'orders#complete', on: :collection
  end
  resources :promos
  resources :videos
  resources :experts
  resources :subscriptions do
      get 'section/:id'=>'subscriptions#section', on: :collection
      get 'send'=>'subscriptions#send_mail', on: :collection
  end
  resources :medicaments

  resources :certificates do
      get 'set'=>'certificates#set', on: :collection
      get 'sum'=>'certificates#sum', on: :collection
  end

  post 'api/metrika/register'=>'metrika#register', as: :metrika_register
  get 'services/79-lasernaya-epilyaciya.html' => 'services#lazer', as: :lazerepil
  get 'services/:id-:url.html'=>'services#show', as: :service,  :constraints => {:id => /\d+/}
  get 'services'=>'services#index', as: :services
  get 'services/prices'=>'services#prices', as: :prices_services

  get 'issues/:url.html'=>'issues#show', as: :issue, :constraints => {:url => /.*/}
  get 'issues'=>'issues#index', as: :issues

  get 'section/:url.html'=>'sections#show', as: :section

  mount RedactorRails::Engine => '/redactor_rails'
  ActiveAdmin.routes(self)
  devise_for :users
  resources :categories

  resources :posts

  root 'posts#root'
  get 'responces'=>'posts#reviews', as: :responces
  get 'news'=>'posts#news', as: :news
  get 'contacts'=>'posts#contacts', as: :contacts_index
  get 'contacts/:id'=>'posts#contacts', as: :contacts
  get 'thanks'=>'posts#thanks', as: :thanks
  get 'gallery'=>'posts#gallery', as: :gallery

  get 'shop'=>'shop#main', as: :shop
  get 'store'=>'shop#index', as: :shop_index
  get 'shop/search'=>'shop#search', as: :shop_search
  get 'shop/bestsellers'=>'shop#best_sellers', as: :shop_best_sellers
  get 'shop/collection/:url'=>'shop#collection', as: :shop_collection
  get 'shop/product/:url.html'=>'shop#product', as: :shop_product
  get 'shop/data/cart'=>'shop#cart_data'
  get 'shop/cart'=>'shop#cart', as: :shop_cart
  get 'shop/order/:id'=>'shop#order', as: :shop_order
  get 'shop/orders'=>'shop#orders', as: :shop_orders
  get 'shop/:url'=>'shop#unit', as: :shop_unit
  get 'about'=>'posts#about', as: :about

  get 'api/typehead/services'=>'services#typehead_list', as: :api_typehead_services

  get 'services/lazer.html' => 'services#lazer', as: :services_lazer

  namespace :manager do
      resources :orders
      resources :prices
      resources :users
      get 'metrika' => 'metrika#index'
      get 'metrika/service/all' => 'metrika#all'
      get 'metrika/service/:service_id' => 'metrika#service'
      namespace :shop do
        resources :categories
        resources :products do
          post :update_field, on: :collection
        end
        namespace :product do
          resources :items
        end
      end
  end

  get 'private/profile'=>'private#profile', as: :private_profile

  get '/404' => 'errors#not_found'
  get '/422' => 'errors#server_error'
  get '/500' => 'errors#server_error'

  get '/fotoepilyatsiya-na-apparate-record-618.html', to: redirect('/services/1-fotoepilyacia.html')
  get '/prajs.html', to: redirect('/services/prices')
  get '/pedikyur.html', to: redirect('/services/57-pedikyur-klassicheskij-kazan.html')
  get '/credstva-protiv-vrastaniya-volos-i-zamedlyayushchie-rost-volos.html', to: redirect('/services/79-lasernaya-epilyaciya.html')
  get '/disport-botoks.html', to: redirect('/services/16-botulotoksiny.html')
  get '/obertyvanie-tela/98-obertyvanie-vsego-tela-listovymi-vodoroslyami.html', to: redirect('/services/25-obertyvanie-vsego-tela-listovymi-vodoroslyami.html')
  get '/plazmolifting/163-o-metode-plasmolifting-v-trikhologii.html', to: redirect('/services/28-o-metode-plasmolifting-v-trikhologii.html')
  get '/lechebnyj-manikyur-yaponskij-goryachij/79-yaponskij-manikyur-kazan.html', to: redirect('/services/63-yaponskij-manikyur-kazan.html')
  get '/spetsialisty.html', to: redirect('/experts/')
  get '/chistki-litsa.html', to: redirect('/services/6-chistka-lica.html')
  get '/depilyatsiya/162-shugaring.html', to: redirect('/services/3-saharnaya-epilyacia.html')
  get '/kontakty.html', to: redirect('/contacts')
  get '/konsultatsiya-dermatologa-kosmetologa.html', to: redirect('/services/5-konsultaciya-kosmetologa.html')
  get '/voskovaya-epilyatsiya.html', to: redirect('/services/2-voskovaya-epilyacia.html')
  get '/konturnaya-plastika-korrektsiya-fillerami.html', to: redirect('/services/12-konturnaya-plastika-korrektsiya-fillerami.html')
  get '/otzyvy.html', to: redirect('/responces')
  get '/mezoterapiya-litsa.html', to: redirect('/services/14-mezoterapiya.html')
  get '/pedikyur/76-apparatnyj-pedikyur-kazan.html', to: redirect('/services/59-apparatnyj-pedikyur-kazan.html')
  get '/mezoterapiya-litsa/132-f-btx-gialuronovaya-kislota-peptidy.html', to: redirect('/services/14-mezoterapiya.html')
  get '/biorevitalizatsiya.html', to: redirect('/services/15-biorevitalizacia.html')
  get '/massazh-tela.html', to: redirect('/services/38-massag-tela.html')

end

app/models/promo.rb
class Promo < ActiveRecord::Base
  has_attached_file :photo, :styles => { :medium => "300x300", :thumb => "100x100" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
  has_and_belongs_to_many :services
  has_many :widgets, primary_key: :id, foreign_key: :entity_id
  accepts_nested_attributes_for :services, allow_destroy: true
  default_scope where('due > ?',Date.today)

  def is_alive
      self.due > Time.now
  end
end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
    def index
        @promos = Promo.where('fl_active = 1 AND fl_menu = 1').order('fl_order ASC')
    end

    def show
        @promo = Promo.find(params[:id])
        @promos = Promo.where('fl_active = 1 AND NOT (id = ?)',@promo.id).order('fl_order ASC').limit(3)
    end

    def top_banner

    end
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/views/promos/index.html.erb
<%
   meta :title => 'Акции Центра эпиляции и косметологии',
        :description => 'Текущие акции, скидки и специальные предложения от центра эпиляции и косметологии'
%>
<div class="main col-md-12" id="promos">
  <!-- page-title ddd start -->
  <!-- ================ -->
  <h1 class="page-title">Акции Центра эпиляции и косметологии</h1>
  <div class="separator-2"></div>
  <div class="section">
        <% if @promos.each do |banner|%>
                <div class="row call-to-action" style="margin-top: 40px;border: 3px solid #f2dede;padding: 10px;">
                  <div class="col-md-4">
                    <%=image_tag 'http://kosmetologiya-kazan.ru/' + banner.photo.url(:medium), class: 'img-responsive'%>
                  </div>
                  <div class="col-md-8" style="padding-top: 15px;text-align: left;">
                    <%=banner.banner.html_safe%>
                    <div style="float: left;" class="btn-danger btn  btn-md">До <%=banner.due.strftime('%d.%m.%Y')%></div>
                    <div style="float: left;">
                      <button data-toggle="modal" data-target="#online-order" class="btn btn-success btn-md">Записаться</button>
                      <a href="<%if banner.more_link == nil || banner.more_link.length == 0%>/promos/<%=banner.id%><% else %><%=banner.more_link%><% end %>" class="btn btn-warning btn-md" style="background-color: #fcf8e3;color: #000000 ">Подробнее</a>
                    </div>
                  </div>
                </div>
        <% end.empty? %>
            <div class="text-center" style="padding: 50px;">К сожалению, в данный момент никаких акций не проводится</div>
        <% end %>
  </div>
</div>

app/views/promos/show.html.erb
<%
   meta :title => "Акция - #{@promo.name}",
        :description => Sanitize.clean(@promo.content).gsub("\n"," ").truncate(250)

   content = @promo.content
   content = content.gsub(/<\/?span[^>]*>/i,'')
%>
<div class="main col-md-8">
  <!-- page-title start -->
  <!-- ================ -->
  <h1 class="page-title"><%=@promo.name%></h1>
  <!-- page-title end -->

  <!-- blogpost start -->
  <article class="clearfix blogpost full" style="padding-top: 20px;">
    <div class="blogpost-body">
      <div class="blogpost-content">
        <%=content.html_safe%>
            <a href="javascript://" class="btn btn-lg btn-success" data-toggle="modal" data-target="#recall">Забронировать</a>
      </div>
    </div>
  </article>
</div>
<aside class="col-md-3 col-md-offset-1">
  <div class="sidebar">
    <h3 class="title">Ещё акции</h3>
    <div class="separator"></div>
    <%@promos.each_with_index do |promo,index|%>
        <div class="block clearfix">
          <div class="image-box">
            <div class="overlay-container">
              <img src="<%=promo.photo.url(:medium)%>" alt="">
              <div class="overlay">
                <div class="overlay-links">
                  <%=link_to promo_path(promo) do %><i class="fa fa-link"></i><% end %>
                  <a href="<%=promo.photo.url%>" class="popup-img-single" title="image title"><i class="fa fa-search-plus"></i></a>
                </div>
              </div>
            </div>
            <div class="image-box-body">
              <h3 class="title"><%=link_to promo.name, promo_path(promo)%></h3>
            </div>
          </div>
          <br>
    <% end %>
    </div>
  </div>
</aside>